# Set the theme to Architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Site settings
title: Your Site Title
description: A short description of your site.
url: "https://yourusername.github.io" # replace with your GitHub Pages URL
baseurl: "" # leave blank for user repositories

# Exclude specific files or folders from the site
exclude:
  - README.md # optionally exclude the README from being shown on the site

# Disable any downloads or buttons if the theme has such features
show_download_buttons: false
